spring.application.name=FederalHolidayAssessment
springdoc.swagger-ui.path=/swagger-ui.html

# Custom path for the raw underlying OpenAPI JSON definitions metadata
springdoc.api-docs.path=/api-docs

# Sort the endpoints alphabetically by HTTP Method (GET, POST, etc.)
springdoc.swagger-ui.operationsSorter=alpha
